
# main page
default:
    path: /
    controller: App\Bundle\Dashboard\Web\Controllers\MainController::index

admin_dashboard:
    prefix: '/admin'
    resource: "../../src/Bundle/Dashboard/Admin/config/routes.yaml"

rails:
    resource: "../../src/Bundle/Rails/Web/config/routes.yaml"

article:
    resource: "@ArticleBundle/Resources/config/routing/all.yaml"

messenger:
    resource: "@MessengerBundle/Resources/config/routing/all.yaml"

user:
    resource: "@UserBundle/Resources/config/routing/all.yaml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
